- name: Instalar pacotes necessários para LVM
  apt:
    name: lvm2
    state: present

- name: Criar Volume Group
  lvg:
    vg: dados
    pvs:
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd

- name: Criar Logical Volume
  community.general.lvol:
    vg: dados
    lv: sistema
    size: 15g

- name: Formatar e montar
  filesystem:
    fstype: ext4
    dev: /dev/dados/sistema

- name: Montar automaticamente
  mount:
    path: /dados
    src: /dev/dados/sistema
    fstype: ext4
    opts: defaults
    state: mounted

