- name: Instalar pacotes necessários para LVM
  apt:
    name: lvm2
    state: present

- name: Criar Volume Group chamado "dados"
  lvg:
    vg: dados
    pvs:
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd

- name: Criar Logical Volume "sistema"
  community.general.lvol:
    vg: dados
    lv: sistema
    size: 15g

- name: Formatar o LV "sistema" como ext4
  filesystem:
    fstype: ext4
    dev: "/dev/dados/sistema"

- name: Configurar montagem automática no /etc/fstab
  lineinfile:
    path: /etc/fstab
    line: "/dev/dados/sistema /dados ext4 defaults 0 0"

- name: Criar diretório /dados e montar a partição
  file:
      path: /dados
      state: directory
  notify: Montar partição

