Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.network "private_network", ip: "192.168.57.10"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "p01_isabel"
    vb.memory = 1024
  end
  config.vm.disk :disk, size: "10GB", name: "disk1"
  config.vm.disk :disk, size: "10GB", name: "disk2"
  config.vm.disk :disk, size: "10GB", name: "disk3"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end

