- name: Configurar SSH
  block:
    - name: Permitir apenas chaves públicas
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"

    - name: Bloquear root via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"

    - name: Reiniciar serviço SSH
      service:
        name: ssh
        state: restarted

